Frontend:
  impl: LoadStoreTrace
  clock_ratio: 8
  num_expected_insts: 1000000
  path: final_W_traces/600.trace
  Translation:
    impl: NoTranslation
    max_addr: 2147483648
              

MemorySystem:
  impl: GenericDRAM
  clock_ratio: 3

  DRAM:
    impl: DDR5
    org:
      preset: DDR5_16Gb_x4
      channel: 1
      rank: 2
    timing:
      preset: DDR5_1600AN
    RFM:
      BRC: 2

  Controller:
    impl: Generic
    Scheduler:
      impl: FRFCFS
    RefreshManager:
      impl: AllBank
    RowPolicy:
      impl: OpenRowPolicy
      cap: 4
    plugins:
    

  AddrMapper:
    impl: MOP4CLXOR
